'use strict';

var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

//The keys follow a different format than the other models
//This is due to the response from plugnpay
var TransactionSchema = new Schema({
  FinalStatus: String,
  IPaddress: String,
  MStatus: String,
  "User-Agent": String,
  acct_code4: String,
  accttype: {type:String, default: 'credit'},
  amountcharged: String,
  "auth-code": String,
  "auth-msg": String,
  auth_date: String,
  "avs-code": String,
  "card-address1": String,
  "card-address2": String,
  "card-amount": String,
  "card-city": String,
  "card-exp": String,
  "card-name": String,
  "card-type": String,
  "card-zip": String,
  currency: String,
  cvvresp: String,
  easycart: String,
  merchant: String,
  merchfraudlev: String,
  mode: String,
  orderID: String,
  "publisher-name": String,
  receiptcc: String,
  "resp-code": String,
  shipinfo: String,
  sresp: String,
  success: String,
  a: String
});

module.exports = mongoose.model('Transaction', TransactionSchema);



//  FinalStatus:      nil,    # "success",
//  IPaddress:        nil,    # "71.42.213.98",
//  MStatus:          nil,    # "success",
//  "User-Agent":     nil,    # "hackney/0.11.1",
//  a:                nil,    # "b\n",
//  acct_code3:       nil,    # "newcard",
//  acct_code4:       nil,    # "pnpremote.cgi",
//  amountcharged:    nil,    # "123.45",
//  "auth-code":      nil,    # "TSTAUT",
//  "auth-msg":       nil,    # " ",
//  auth_date:        nil,    # "20140520",
//  "avs-code":       nil,    # "A",
//  "card-address1":  nil,    # "123 ABC St",
//  "card-amount":    nil,    # "123.45",
//  "card-city":      nil,    # "Miami",
//  "card-exp":       nil,    # "05/17",
//  "card-name":      nil,    # "Joe Test",
//  "card-state":     nil,    # "FL",
//  "card-type":      nil,    # "VISA",
//  "card-zip":       nil,    # "33126",
//  checktype:        nil,    # "WEB",
//  currency:         nil,    # "usd",
//  cvvresp:          nil,    # "M",
//  easycart:         nil,    # "0",
//  fexpt:            nil,    # "yes",
//  merchant:         nil,    # "pnpdemo2",
//  merchfraudlev:    nil,    # "3",
//  mode:             nil,    # "auth",
//  orderID:          nil,    # "2014052015023407806",
//  "publisher-name": nil,    # "pnpdemo2",
//  receiptcc:        nil,    # "XXXXXXXXXXXX1111",
//  "resp-code":      nil,    # "00",
//  resphash:         nil,    # "a0b0ff97ab27a7379c55609aa70cabef",
//  shipinfo:         nil,    # "0",
//  sresp:            nil,    # "A",
//  success:          nil,    # "yes"
//time_stamp:       time_stamp,
